# Generated by Django 4.0.4 on 2022-04-20 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='titre')),
                ('start_point', models.CharField(max_length=200, verbose_name='point de départ')),
                ('description', models.CharField(max_length=400)),
                ('start_alt', models.FloatField(verbose_name='altitude de départ (m)')),
                ('alt_min', models.FloatField(verbose_name='altitude min (m)')),
                ('alt_max', models.FloatField(verbose_name='altitude max (m)')),
                ('elevation_gain', models.FloatField(verbose_name='dénivelé positif cumulé (m)')),
                ('elevation_loss', models.FloatField(verbose_name='dénivelé négatif cumulé (m)')),
                ('duration', models.FloatField(verbose_name='durée estimée (h)')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='difficulté')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField(verbose_name='date de la sortie')),
                ('duration', models.FloatField(verbose_name='durée réelle (h)')),
                ('np_participant', models.IntegerField(verbose_name='nombre de participant')),
                ('group_exp', models.CharField(choices=[('BEG', 'Tous débutants'), ('EXP', 'Tous expérimentés'), ('MIX', 'Mixte')], max_length=3, verbose_name='expérience du groupe')),
                ('weather', models.CharField(choices=[('BAD', 'Mauvaise'), ('AVG', 'Moyenne'), ('WEL', 'Bonne')], max_length=3, verbose_name='météo')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='difficulté ressentie')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
