# Generated by Django 4.0.4 on 2022-04-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortie',
            old_name='user',
            new_name='utilisateur',
        ),
    ]
