# Generated by Django 4.0.4 on 2022-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_rename_user_sortie_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortie',
            old_name='np_participant',
            new_name='nb_participant',
        ),
        migrations.AlterField(
            model_name='sortie',
            name='group_exp',
            field=models.CharField(choices=[('Tous débutants', 'Tous débutants'), ('Tous expérimentés', 'Tous expérimentés'), ('Mixte', 'Mixte')], max_length=30, verbose_name='expérience du groupe'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='weather',
            field=models.CharField(choices=[('Mauvaise', 'Mauvaise'), ('Moyenne', 'Moyenne'), ('Bonne', 'Bonne')], max_length=30, verbose_name='météo'),
        ),
    ]
